# Generated by Django 5.2.8 on 2025-11-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_userprofile_age_userprofile_gender_userprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_mood",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_mood_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="wallet_minutes",
            field=models.PositiveIntegerField(default=45),
        ),
    ]
