# Generated by Django 5.2.8 on 2025-11-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emailotp'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='api_emailot_email_ab57e8_idx',
            old_name='api_emailot_email_f7068d_idx',
        ),
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='api_emailot_token_79673b_idx',
            old_name='api_emailot_token_02bc1e_idx',
        ),
    ]
