# Generated by Django 5.2.8 on 2025-11-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_api_emailot_email_f7068d_idx_api_emailot_email_ab57e8_idx_and_more'),
        ('api', '0007_seed_admin_account'),
    ]

    operations = [
    ]
