# Generated by Django 5.2.8 on 2025-11-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_meditationsession_id_alter_mindcarebooster_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mood_updates_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mood_updates_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
